### ISSUE TITLE
[Bug] Turning off Apple ads package still runs source freshness

### ISSUE THREAD

**Issue by nszoni** [fivetran/dbt_ad_reporting#73] opened 2022-12-26 16:06 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

Turning off the usage of Apple ads platform as stated in the package README doesn't actually turn off source freshness tests for the models, although the config is conditioned on the variable set to `False`

```yml
sources:
  - name: apple_search_ads
    schema: "{{ var('apple_search_ads_schema', 'apple_search_ads') }}"
    database: "{% if target.type != 'spark'%}{{ var('apple_search_ads_database', target.database) }}{% endif %}"

    loader: Fivetran
    loaded_at_field: _fivetran_synced

    freshness: 
      warn_after: {count: 48, period: hour}
      error_after: {count: 168, period: hour}

    config:
      enabled: "{{ var('ad_reporting__apple_search_ads_enabled', true) }}"
```

### Relevant error log or model output

```shell
15:27:40  1 of 36 START freshness of apple_search_ads.search_term_report ................. [RUN]
15:27:41  1 of 36 ERROR freshness of apple_search_ads.search_term_report ................. [ERROR in 0.68s]

15:27:50  Runtime Error in source search_term_report (models/src_apple_search_ads.yml)
15:27:50    404 Not found: Dataset xxxxx:apple_search_ads was not found in location US
15:27:50    
15:27:50    (job ID: b656a397-d0c4-4f36-b651-898edfaf03cb)
15:27:50  
15:27:50  
15:27:50  Done.
```

### Expected behavior

I would expect dbt not running source freshness tests for Apple because we are not creating those.

### dbt Project configurations

```yml
vars:
  ad_reporting__apple_search_ads_enabled: False
  ad_reporting__pinterest_ads_enabled: false
  ad_reporting__linkedin_ads_enabled: false
  ad_reporting__twitter_ads_enabled: false
  ad_reporting__snapchat_ads_enabled: false
  ad_reporting__tiktok_ads_enabled: false

  apple_search_ads__using_search_terms: False
```

### Package versions

```yml
packages:
  - package: calogica/dbt_date
    version: [">=0.5.0", "<0.6.0"]
  - package: dbt-labs/dbt_utils
    version: [">=0.8.0", "<0.9.0"]
  - package: dbt-labs/codegen
    version: [">=0.7.0", "<0.8.0"]
  - package: fivetran/shopify
    version: [">=0.6.0", "<0.7.0"]
  - package: fivetran/google_ads
    version: [">=0.8.0", "<0.9.0"]
  - package: fivetran/google_ads_source
    version: [">=0.8.0", "<0.9.0"]
  - package: fivetran/microsoft_ads
    version: [">=0.5.0", "<0.6.0"]
  - package: fivetran/facebook_ads
    version: [">=0.5.0", "<0.6.0"]
  - package: fivetran/ad_reporting
    version: [">=1.0.0", "<1.1.0"]
  - package: calogica/dbt_expectations
    version: [">=0.5.0", "<0.6.0"]
# - package: fivetran/klaviyo
#   version: [">=0.4.0", "<0.5.0"]
  - package: dbt-labs/segment
    version: [">=0.8.0", "<0.9.0"]
  - package: fivetran/instagram_business
    version: [">=0.1.0", "<0.2.0"]
  - package: fivetran/fivetran_utils
    version: [">=0.3.0", "<0.4.0"]
  - package: dbt-labs/metrics
    version: [">=0.3.0", "<0.4.0"]

```

### What database are you using dbt with?

bigquery

### dbt Version

```bash
❯ dbt --version
Core:
  - installed: 1.2.0
  - latest:    1.3.1 - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

Plugins:
  - bigquery: 1.2.0 - Update available!
 ```

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [X] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.

**Comment by fivetran-joemarkiewicz** [comment] 2023-01-03 15:08
Hi @nszoni thanks so much for opening this Issue and I am sorry you are experiencing this bug.

I would believe the inclusion of the `ad_reporting__apple_search_ads_enabled: False` would properly disable the entire apple ad source file and not run the source freshness.

Before delving too deep I am curious about one item in particular. Would you be able to try and lowercase the `false` in your variable declarations for the apple ads variables. I have experienced dbt getting confused with the mixed casing in the past and want to rule that out initially.

**Comment by nszoni** [comment] 2023-01-04 08:20
hey @fivetran-joemarkiewicz thanks for taking this up! I've tried keeping all of them lowercase, but it still wants to check the apple ad source.

![75820](https://user-images.githubusercontent.com/47299073/210512707-40134024-fd0a-4f41-bcb4-5df4096bcc82.png)

**Comment by fivetran-joemarkiewicz** [comment] 2023-01-04 15:50
Hi @nszoni thanks for checking my suspicious and showing that there is something more going on here. I have been able to replicate your variables in my local environment and notice the same error you are seeing.

I have been able to narrow the issue down to [this line](https://github.com/fivetran/dbt_apple_search_ads_source/blob/69c8873ba655180a8807dcc61ebc790b680fe00d/models/src_apple_search_ads.yml#L210) within the Apple Search Ads Source package. 

Our intention is that this enablement would be disabled if either (or both) the apple search variables are set to `false`. However, after checking the under the hood rendering, it looks like it simply returns as `False and False` which does not in fact disable the source freshness. I am currently tinkering to see what new config would work to achieve the expected outcome we are looking for. I will be sure the share an update once I find the fix!

**Comment by nszoni** [comment] 2023-01-04 21:53
@fivetran-joemarkiewicz nice catch! I will also keep investigating if i find something else:) Thanks!

**Comment by fivetran-joemarkiewicz** [comment] 2023-01-04 21:57
Looks like my team and I were able to find the root cause! When we adjusted the line noted above to be the below snippet it worked as intended!
```yml
        config:
          enabled: "{{ var('ad_reporting__apple_search_ads_enabled', true) and var('apple_search_ads__using_search_terms', true) }}"
```

This should result in a quick update to the apple_search_ads_source package to use the above line in place of what we currently have.

I noticed you are open to creating a PR to fix this issue. Would you be interested in opening a PR on our Apple Search Ads Source package to address this? Otherwise we can fold this update into our coming sprint.

**Comment by nszoni** [comment] 2023-01-04 21:58
Awesome! Sure thing! Will do it tomorrow:) Thanks a ton!

**Comment by nszoni** [comment] 2023-01-05 10:52
@jonatfivetran here you go!:) 👆

**Comment by fivetran-joemarkiewicz** [comment] 2023-01-06 17:00
Thanks again for the contributor @nszoni 🏅 

Now that the apple_search_ads_source PR has been merged and released, this issue should be resolved. Closing out this issue. Please feel free to reopen if the issue persists.

**Closed by fivetran-joemarkiewicz** 2023-01-06 17:00 UTC
Labels: type:bug, priority:p2, status:scoping, update_type:testing
